# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse-server:8123
    isDefault: true
    jsonData:
      defaultDatabase: default
      server: clickhouse-server
      username: admin
      secure: false
      logs:
        defaultDatabase: default
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
      traces:
        defaultDatabase: default
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
    secureJsonData:
      password: admin
    editable: true

